FROM ubuntu:14.04

ARG SITE_NAME
ARG SERVER_ADMIN
ARG SERVER_LOCALE
ARG APACHE_LOG_DIR

ENV SITE_NAME ${SITE_NAME}
ENV SERVER_ADMIN ${SERVER_ADMIN}
ENV APACHE_LOG_DIR ${APACHE_LOG_DIR}

# Install packages
RUN locale-gen ${SERVER_LOCALE}
RUN export LANG=${SERVER_LOCALE}
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install curl nano apache2 mysql-client openssh-server python-setuptools software-properties-common
RUN DEBIAN_FRONTEND=noninteractive LC_ALL=${SERVER_LOCALE} add-apt-repository ppa:ondrej/php
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install libapache2-mod-php7.0 php7.0-mysql php7.0-gd php-pear php-apc php7.0-curl php7.0-intl php7.0-soap php7.0-zip php7.0-xml php7.0-cli php7.0-common php7.0-json php7.0-opcache php7.0-readline
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer
RUN wget https://phar.phpunit.de/phpunit.phar \
    && chmod +x phpunit.phar \
    && mv phpunit.phar /usr/local/bin/phpunit

# Enable apache mods
RUN a2enmod php7.0
RUN a2enmod rewrite

# Update the PHP.ini file
RUN sed -i "s/error_reporting = .*$/error_reporting = E_ERROR | E_WARNING | E_PARSE/" /etc/php/7.0/apache2/php.ini
RUN sed -i 's/\;date\.timezone\ \=/date\.timezone\ \=\ Europe\/Paris/g' /etc/php/7.0/apache2/php.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer

# Add site to the container
ADD www /var/www/${SITE_NAME}

# Update the default apache with the custom configuration
ADD apache-config.conf /etc/apache2/sites-enabled/000-default.conf

# By default, simply start apache
CMD /usr/sbin/apache2ctl -D FOREGROUND

EXPOSE 80
EXPOSE 22
